import 'package:scripture_daily/models/models.dart';

class BibleData {
  static const List<BibleVersion> versions = [
    BibleVersion(id: 'kjv',        name: 'King James Version',              abbreviation: 'KJV',      language: 'English',    languageCode: 'en'),
    BibleVersion(id: 'web',        name: 'World English Bible',             abbreviation: 'WEB',      language: 'English',    languageCode: 'en'),
    BibleVersion(id: 'bbe',        name: 'Bible in Basic English',          abbreviation: 'BBE',      language: 'English',    languageCode: 'en'),
    BibleVersion(id: 'asv',        name: 'American Standard Version',       abbreviation: 'ASV',      language: 'English',    languageCode: 'en'),
    BibleVersion(id: 'clementine', name: 'Latin Vulgate',                   abbreviation: 'Vulgate',  language: 'Latin',      languageCode: 'la'),
    BibleVersion(id: 'almeida',    name: 'João Ferreira de Almeida',        abbreviation: 'JFA',      language: 'Português',  languageCode: 'pt'),
    BibleVersion(id: 'rccv',       name: 'Romanian Corrected Cornilescu',   abbreviation: 'RCCV',     language: 'Română',     languageCode: 'ro'),
  ];

  static const List<Map<String, String>> allLanguages = [
    {'code': 'en',  'name': 'English',           'flag': '🇬🇧'},
    {'code': 'yo',  'name': 'Yorùbá',             'flag': '🇳🇬'},
    {'code': 'ha',  'name': 'Hausa',              'flag': '🇳🇬'},
    {'code': 'ig',  'name': 'Igbo',               'flag': '🇳🇬'},
    {'code': 'fr',  'name': 'Français',           'flag': '🇫🇷'},
    {'code': 'es',  'name': 'Español',            'flag': '🇪🇸'},
    {'code': 'pt',  'name': 'Português',          'flag': '🇵🇹'},
    {'code': 'de',  'name': 'Deutsch',            'flag': '🇩🇪'},
    {'code': 'it',  'name': 'Italiano',           'flag': '🇮🇹'},
    {'code': 'nl',  'name': 'Nederlands',         'flag': '🇳🇱'},
    {'code': 'pl',  'name': 'Polski',             'flag': '🇵🇱'},
    {'code': 'ru',  'name': 'Русский',            'flag': '🇷🇺'},
    {'code': 'uk',  'name': 'Українська',         'flag': '🇺🇦'},
    {'code': 'ro',  'name': 'Română',             'flag': '🇷🇴'},
    {'code': 'cs',  'name': 'Čeština',            'flag': '🇨🇿'},
    {'code': 'sk',  'name': 'Slovenčina',         'flag': '🇸🇰'},
    {'code': 'hu',  'name': 'Magyar',             'flag': '🇭🇺'},
    {'code': 'hr',  'name': 'Hrvatski',           'flag': '🇭🇷'},
    {'code': 'sr',  'name': 'Српски',             'flag': '🇷🇸'},
    {'code': 'bg',  'name': 'Български',          'flag': '🇧🇬'},
    {'code': 'el',  'name': 'Ελληνικά',           'flag': '🇬🇷'},
    {'code': 'tr',  'name': 'Türkçe',             'flag': '🇹🇷'},
    {'code': 'ar',  'name': 'العربية',             'flag': '🇸🇦'},
    {'code': 'fa',  'name': 'فارسی',               'flag': '🇮🇷'},
    {'code': 'he',  'name': 'עברית',              'flag': '🇮🇱'},
    {'code': 'hi',  'name': 'हिन्दी',              'flag': '🇮🇳'},
    {'code': 'bn',  'name': 'বাংলা',              'flag': '🇧🇩'},
    {'code': 'ta',  'name': 'தமிழ்',              'flag': '🇮🇳'},
    {'code': 'te',  'name': 'తెలుగు',             'flag': '🇮🇳'},
    {'code': 'ml',  'name': 'മലയാളം',             'flag': '🇮🇳'},
    {'code': 'kn',  'name': 'ಕನ್ನಡ',              'flag': '🇮🇳'},
    {'code': 'mr',  'name': 'मराठी',              'flag': '🇮🇳'},
    {'code': 'gu',  'name': 'ગુજરાતી',            'flag': '🇮🇳'},
    {'code': 'pa',  'name': 'ਪੰਜਾਬੀ',             'flag': '🇮🇳'},
    {'code': 'ur',  'name': 'اردو',               'flag': '🇵🇰'},
    {'code': 'sw',  'name': 'Kiswahili',          'flag': '🇰🇪'},
    {'code': 'am',  'name': 'አማርኛ',              'flag': '🇪🇹'},
    {'code': 'so',  'name': 'Soomaali',           'flag': '🇸🇴'},
    {'code': 'af',  'name': 'Afrikaans',          'flag': '🇿🇦'},
    {'code': 'zu',  'name': 'isiZulu',            'flag': '🇿🇦'},
    {'code': 'xh',  'name': 'isiXhosa',           'flag': '🇿🇦'},
    {'code': 'tw',  'name': 'Twi',                'flag': '🇬🇭'},
    {'code': 'ak',  'name': 'Akan',               'flag': '🇬🇭'},
    {'code': 'ln',  'name': 'Lingála',            'flag': '🇨🇩'},
    {'code': 'rw',  'name': 'Kinyarwanda',        'flag': '🇷🇼'},
    {'code': 'mg',  'name': 'Malagasy',           'flag': '🇲🇬'},
    {'code': 'zh',  'name': '中文 (简体)',          'flag': '🇨🇳'},
    {'code': 'zh-tw','name': '中文 (繁體)',         'flag': '🇹🇼'},
    {'code': 'ja',  'name': '日本語',              'flag': '🇯🇵'},
    {'code': 'ko',  'name': '한국어',              'flag': '🇰🇷'},
    {'code': 'vi',  'name': 'Tiếng Việt',         'flag': '🇻🇳'},
    {'code': 'th',  'name': 'ภาษาไทย',            'flag': '🇹🇭'},
    {'code': 'id',  'name': 'Bahasa Indonesia',   'flag': '🇮🇩'},
    {'code': 'ms',  'name': 'Bahasa Melayu',      'flag': '🇲🇾'},
    {'code': 'tl',  'name': 'Filipino',           'flag': '🇵🇭'},
    {'code': 'km',  'name': 'ភាសាខ្មែរ',          'flag': '🇰🇭'},
    {'code': 'my',  'name': 'မြန်မာဘာသာ',         'flag': '🇲🇲'},
    {'code': 'si',  'name': 'සිංහල',              'flag': '🇱🇰'},
    {'code': 'ne',  'name': 'नेपाली',             'flag': '🇳🇵'},
    {'code': 'mn',  'name': 'Монгол',             'flag': '🇲🇳'},
    {'code': 'ka',  'name': 'ქართული',            'flag': '🇬🇪'},
    {'code': 'hy',  'name': 'Հայերեն',            'flag': '🇦🇲'},
    {'code': 'az',  'name': 'Azərbaycanca',       'flag': '🇦🇿'},
    {'code': 'kk',  'name': 'Қазақша',            'flag': '🇰🇿'},
    {'code': 'uz',  'name': 'Oʻzbekcha',          'flag': '🇺🇿'},
    {'code': 'tk',  'name': 'Türkmençe',          'flag': '🇹🇲'},
    {'code': 'sq',  'name': 'Shqip',              'flag': '🇦🇱'},
    {'code': 'mk',  'name': 'Македонски',         'flag': '🇲🇰'},
    {'code': 'la',  'name': 'Latina',             'flag': '🇻🇦'},
    {'code': 'cy',  'name': 'Cymraeg',            'flag': '🏴󠁧󠁢󠁷󠁬󠁳󠁿'},
    {'code': 'ga',  'name': 'Gaeilge',            'flag': '🇮🇪'},
  ];

  static const List<BibleBook> books = [
    BibleBook(id: 'Genesis',          name: 'Genesis',          testament: 'OT', chapters: 50),
    BibleBook(id: 'Exodus',           name: 'Exodus',           testament: 'OT', chapters: 40),
    BibleBook(id: 'Leviticus',        name: 'Leviticus',        testament: 'OT', chapters: 27),
    BibleBook(id: 'Numbers',          name: 'Numbers',          testament: 'OT', chapters: 36),
    BibleBook(id: 'Deuteronomy',      name: 'Deuteronomy',      testament: 'OT', chapters: 34),
    BibleBook(id: 'Joshua',           name: 'Joshua',           testament: 'OT', chapters: 24),
    BibleBook(id: 'Judges',           name: 'Judges',           testament: 'OT', chapters: 21),
    BibleBook(id: 'Ruth',             name: 'Ruth',             testament: 'OT', chapters: 4),
    BibleBook(id: '1+Samuel',         name: '1 Samuel',         testament: 'OT', chapters: 31),
    BibleBook(id: '2+Samuel',         name: '2 Samuel',         testament: 'OT', chapters: 24),
    BibleBook(id: '1+Kings',          name: '1 Kings',          testament: 'OT', chapters: 22),
    BibleBook(id: '2+Kings',          name: '2 Kings',          testament: 'OT', chapters: 25),
    BibleBook(id: '1+Chronicles',     name: '1 Chronicles',     testament: 'OT', chapters: 29),
    BibleBook(id: '2+Chronicles',     name: '2 Chronicles',     testament: 'OT', chapters: 36),
    BibleBook(id: 'Ezra',             name: 'Ezra',             testament: 'OT', chapters: 10),
    BibleBook(id: 'Nehemiah',         name: 'Nehemiah',         testament: 'OT', chapters: 13),
    BibleBook(id: 'Esther',           name: 'Esther',           testament: 'OT', chapters: 10),
    BibleBook(id: 'Job',              name: 'Job',              testament: 'OT', chapters: 42),
    BibleBook(id: 'Psalms',           name: 'Psalms',           testament: 'OT', chapters: 150),
    BibleBook(id: 'Proverbs',         name: 'Proverbs',         testament: 'OT', chapters: 31),
    BibleBook(id: 'Ecclesiastes',     name: 'Ecclesiastes',     testament: 'OT', chapters: 12),
    BibleBook(id: 'Song+of+Solomon',  name: 'Song of Solomon',  testament: 'OT', chapters: 8),
    BibleBook(id: 'Isaiah',           name: 'Isaiah',           testament: 'OT', chapters: 66),
    BibleBook(id: 'Jeremiah',         name: 'Jeremiah',         testament: 'OT', chapters: 52),
    BibleBook(id: 'Lamentations',     name: 'Lamentations',     testament: 'OT', chapters: 5),
    BibleBook(id: 'Ezekiel',          name: 'Ezekiel',          testament: 'OT', chapters: 48),
    BibleBook(id: 'Daniel',           name: 'Daniel',           testament: 'OT', chapters: 12),
    BibleBook(id: 'Hosea',            name: 'Hosea',            testament: 'OT', chapters: 14),
    BibleBook(id: 'Joel',             name: 'Joel',             testament: 'OT', chapters: 3),
    BibleBook(id: 'Amos',             name: 'Amos',             testament: 'OT', chapters: 9),
    BibleBook(id: 'Obadiah',          name: 'Obadiah',          testament: 'OT', chapters: 1),
    BibleBook(id: 'Jonah',            name: 'Jonah',            testament: 'OT', chapters: 4),
    BibleBook(id: 'Micah',            name: 'Micah',            testament: 'OT', chapters: 7),
    BibleBook(id: 'Nahum',            name: 'Nahum',            testament: 'OT', chapters: 3),
    BibleBook(id: 'Habakkuk',         name: 'Habakkuk',         testament: 'OT', chapters: 3),
    BibleBook(id: 'Zephaniah',        name: 'Zephaniah',        testament: 'OT', chapters: 3),
    BibleBook(id: 'Haggai',           name: 'Haggai',           testament: 'OT', chapters: 2),
    BibleBook(id: 'Zechariah',        name: 'Zechariah',        testament: 'OT', chapters: 14),
    BibleBook(id: 'Malachi',          name: 'Malachi',          testament: 'OT', chapters: 4),
    BibleBook(id: 'Matthew',          name: 'Matthew',          testament: 'NT', chapters: 28),
    BibleBook(id: 'Mark',             name: 'Mark',             testament: 'NT', chapters: 16),
    BibleBook(id: 'Luke',             name: 'Luke',             testament: 'NT', chapters: 24),
    BibleBook(id: 'John',             name: 'John',             testament: 'NT', chapters: 21),
    BibleBook(id: 'Acts',             name: 'Acts',             testament: 'NT', chapters: 28),
    BibleBook(id: 'Romans',           name: 'Romans',           testament: 'NT', chapters: 16),
    BibleBook(id: '1+Corinthians',    name: '1 Corinthians',    testament: 'NT', chapters: 16),
    BibleBook(id: '2+Corinthians',    name: '2 Corinthians',    testament: 'NT', chapters: 13),
    BibleBook(id: 'Galatians',        name: 'Galatians',        testament: 'NT', chapters: 6),
    BibleBook(id: 'Ephesians',        name: 'Ephesians',        testament: 'NT', chapters: 6),
    BibleBook(id: 'Philippians',      name: 'Philippians',      testament: 'NT', chapters: 4),
    BibleBook(id: 'Colossians',       name: 'Colossians',       testament: 'NT', chapters: 4),
    BibleBook(id: '1+Thessalonians',  name: '1 Thessalonians',  testament: 'NT', chapters: 5),
    BibleBook(id: '2+Thessalonians',  name: '2 Thessalonians',  testament: 'NT', chapters: 3),
    BibleBook(id: '1+Timothy',        name: '1 Timothy',        testament: 'NT', chapters: 6),
    BibleBook(id: '2+Timothy',        name: '2 Timothy',        testament: 'NT', chapters: 4),
    BibleBook(id: 'Titus',            name: 'Titus',            testament: 'NT', chapters: 3),
    BibleBook(id: 'Philemon',         name: 'Philemon',         testament: 'NT', chapters: 1),
    BibleBook(id: 'Hebrews',          name: 'Hebrews',          testament: 'NT', chapters: 13),
    BibleBook(id: 'James',            name: 'James',            testament: 'NT', chapters: 5),
    BibleBook(id: '1+Peter',          name: '1 Peter',          testament: 'NT', chapters: 5),
    BibleBook(id: '2+Peter',          name: '2 Peter',          testament: 'NT', chapters: 3),
    BibleBook(id: '1+John',           name: '1 John',           testament: 'NT', chapters: 5),
    BibleBook(id: '2+John',           name: '2 John',           testament: 'NT', chapters: 1),
    BibleBook(id: '3+John',           name: '3 John',           testament: 'NT', chapters: 1),
    BibleBook(id: 'Jude',             name: 'Jude',             testament: 'NT', chapters: 1),
    BibleBook(id: 'Revelation',       name: 'Revelation',       testament: 'NT', chapters: 22),
  ];

  static List<BibleBook> get oldTestament => books.where((b) => b.testament == 'OT').toList();
  static List<BibleBook> get newTestament => books.where((b) => b.testament == 'NT').toList();

  static const List<String> dailyVerseRefs = [
    'John 3:16', 'Psalm 23:1', 'Romans 8:28', 'Philippians 4:13',
    'Jeremiah 29:11', 'Proverbs 3:5', 'Isaiah 40:31', 'Matthew 6:33',
    'Psalm 46:1', 'Romans 15:13', 'Joshua 1:9', '1 Corinthians 13:4',
    'Psalm 119:105', 'John 14:6', 'Ephesians 2:8', 'Hebrews 11:1',
    'Romans 12:2', 'Galatians 2:20', 'Psalm 91:1', '2 Timothy 1:7',
    'Matthew 11:28', 'John 16:33', 'Proverbs 31:25', 'Isaiah 41:10',
    'Psalm 37:4', 'Romans 5:8', 'Colossians 3:23', 'James 1:2',
    'John 15:5', 'Micah 6:8', 'Psalm 27:1', 'Lamentations 3:22',
  ];
}
