// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqBbCBA2bfiAji5lwYAoGM3uubKCmJvyk',
    appId: '1:125793245556:web:2f4bfc6e68acc7a0323421',
    messagingSenderId: '125793245556',
    projectId: 'obaloluwa-4721f',
    authDomain: 'obaloluwa-4721f.firebaseapp.com',
    storageBucket: 'obaloluwa-4721f.firebasestorage.app',
    measurementId: 'G-L3LJJNT117',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0f3GUM8m4pc4j3pQGwbuf6F-eZ6cf69g',
    appId: '1:125793245556:android:57cf1404bfde0283323421',
    messagingSenderId: '125793245556',
    projectId: 'obaloluwa-4721f',
    storageBucket: 'obaloluwa-4721f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkc_dg4gIHud45VVkAsaTtqjeadIGLlBk',
    appId: '1:125793245556:ios:1eb7e6d6687a56ab323421',
    messagingSenderId: '125793245556',
    projectId: 'obaloluwa-4721f',
    storageBucket: 'obaloluwa-4721f.firebasestorage.app',
    iosClientId: '125793245556-oo8gv1nmqo2jheoaq5pa9qc989qb6dse.apps.googleusercontent.com',
    iosBundleId: 'com.example.bible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkc_dg4gIHud45VVkAsaTtqjeadIGLlBk',
    appId: '1:125793245556:ios:1eb7e6d6687a56ab323421',
    messagingSenderId: '125793245556',
    projectId: 'obaloluwa-4721f',
    storageBucket: 'obaloluwa-4721f.firebasestorage.app',
    iosClientId: '125793245556-oo8gv1nmqo2jheoaq5pa9qc989qb6dse.apps.googleusercontent.com',
    iosBundleId: 'com.example.bible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqBbCBA2bfiAji5lwYAoGM3uubKCmJvyk',
    appId: '1:125793245556:web:82ea4f6a07c0c390323421',
    messagingSenderId: '125793245556',
    projectId: 'obaloluwa-4721f',
    authDomain: 'obaloluwa-4721f.firebaseapp.com',
    storageBucket: 'obaloluwa-4721f.firebasestorage.app',
    measurementId: 'G-JWLP1GWZ0Q',
  );

}